export class BlogModel {
    articles: any = [
        {
            id: "001",
            tutorial: "Business",
            date: "May 19, 2021",
            title: "5 Bad Landing Page Examples & How We Would Fix Them",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            imageURL: "https://images.unsplash.com/photo-1584824486516-0555a07fc511?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80 ",
            author: " Jerome Bell",
            profileImgURL: "https://images.unsplash.com/photo-1597071058713-6776461d7737?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80",
            readTime: '20',
        },
        {
            id: "002",
            tutorial: "Digital",
            date: "May 25 2021",
            title: "Why UX Design Matters and How it Affects Ranking",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            imageURL: "https://images.unsplash.com/photo-1640695186958-470133dee50f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
            author: " Jerome Bell",
            profileImgURL: "https://images.unsplash.com/photo-1603813425271-6ed9a5720f86?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
            readTime: '10',
        },
        {
            id: "003",
            tutorial: "Business",
            date: "May 30 2021",
            title: "This Week in Search: New Limits and Exciting Features",
            description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            imageURL: "https://images.unsplash.com/photo-1635405038683-39ac9c4c70c7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1169&q=80",
            author: "Zyro",
            profileImgURL: "https://images.unsplash.com/photo-1590925942021-1d44c253d204?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=814&q=80",
            readTime: '25',
        },
        // {
        //     id: "002",
        //     tutorial: "",
        //     date: "",
        //     title: "",
        //     description: "",
        //     imageURL: " ",
        //     author: "",
        //     profileImgURL: "",
        // readTime:'',
        // },
    ]
}